### PR TITLE
Feature/ipehr 57

### PR DESCRIPTION
**Pull request by DmitryLakhteen**

### CODE REVIEW

**Comment by 1db1** [comment]
@DmitryLakhteen What is the compression ratio for the test document?

**Comment by DmitryLakhteen** [comment]
> @DmitryLakhteen What is the compression ratio for the test document?

@1db1 5 from config.json.example

**Comment by 1db1** [comment]
I meant how many times the size of the document is reduced? The original size is 287K

**Comment by DmitryLakhteen** [comment]
I added optional skipped test. Ratio is:
Level: 0 Ratio: 1.0 times
Level: 1 Ratio: 12.2 times                                                                                                                                                                                                                         
Level: 2 Ratio: 13.8 times                                                                                                                                                                                                                         
Level: 3 Ratio: 15.9 times                                                                                                                                                                                                                         
Level: 4 Ratio: 15.9 times                                                                                                                                                                                                                         
Level: 5 Ratio: 19.3 times                                                                                                                                                                                                                         
Level: 6 Ratio: 21.7 times                                                                                                                                                                                                                         
Level: 7 Ratio: 22.9 times                                                                                                                                                                                                                         
Level: 8 Ratio: 23.8 times                                                                                                                                                                                                                         
Level: 9 Ratio: 24.7 times

**Comment by 1db1** [comment]
In this test, you encrypt the plain data, and we are saving the encrypted data in the project. Try doing such a test with encrypted data.

**Comment by DmitryLakhteen** [comment]
Interesting... no ratio on any level. I tried rar with maximum settings on this encrypted with chacha_poly document. Rar do not compress too) Looks like compression is not useful option for our data

**Comment by 1db1** [comment]
If you read the task carefully, you will see that documents should be compressed before encryption.

**Comment by DmitryLakhteen** [comment]
FIxed. Compressor moved to docs service

**Pull request merged**
